locale                   : "en-US"
title                    : "Fabien Defrance"
name                     : "Fabien Defrance"
description              : "Quantum sensing & superconducting device physics"
url                      : "https://Fabdef.github.io"
repository               : "Fabdef/Fabdef.github.io"

author:
  name             : "Fabien Defrance"
  avatar           : "profile.png"
  bio              : "Research Scientist - Quantum Sensing, Superconducting Devices, THz Instrumentation"
  location         : "Barcelona, Spain"
  email            : "fabien.defrance@icn2.cat"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:fabien.defrance@icn2.cat"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/fabien-defrance-24778028"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=iGsbyiEAAAAJ&hl=en"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-3746-5296"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown